### ISSUE TITLE
Responsiveness and media queries

### ISSUE THREAD

**Issue by Pencroff** [flexiblegs/flexiblegs-less-plus#1]
Thank you for very good mixins.
Could you help me please. I would like to have responsive grid.
But i don't see any media queries. How I could add it?

**Comment by dnomak** [comment]
flexiblegs-*-plus is the core. There is no need to breakpoint. You can write it yourself.

Example:

``` less
// xl
.products {
  .wrap;
  .wrap(gutter,40);
  .wrap(5);
  &__item {
    .col;
  }
}

// lg
@media (max-width: 1024px) {
  .products {
    .wrap(gutter,24);
    .wrap(4);
  }
}

// md
@media (max-width: 768px) {
  .products {
    .wrap(gutter,16);
    .wrap(3);
  }
}

// sm
@media (max-width: 667px) {
  .products {
    .wrap(gutter,8);
    .wrap(2);
  }
}
```

``` html
<div class="products">
  <div class="products__item">01</div>
  <div class="products__item">02</div>
  <div class="products__item">03</div>
  <div class="products__item">04</div>
  <div class="products__item">05</div>
</div>
```

My english is really bad. I'm sorry for it :(

**Comment by Pencroff** [comment]
Thank you for your feedback. I actually did the same approach. I have decided, that responsiveness should be carefully planned. Any way thanks for good job.

**Comment by dnomak** [comment]
:+1:
