### ISSUE TITLE
.col("hidden") not working properly.

### ISSUE THREAD

**Issue by frankcs** [flexiblegs/flexiblegs-less-plus#2]
I was just following your tutorial on http://flexible.gs/learn/hidden/?preprocessor=less#hidden-less but i can't get this to work. I think i'ts a problem on the `.col` mixin on L:217. I checked the sass implementation and you are using `display:none` there.

**Comment by dnomak** [comment]
thank you tomorrow I fix :)

**Comment by dnomak** [comment]
https://github.com/flexiblegs/flexiblegs-less/commit/b2ab5f63b69e06ba71f084eb789283cbbc53c893#diff-aba7e926962be525d9b7ee91b5f05b90L217
